### ISSUE TITLE
Selection should not be an object that acts like an array

### ISSUE THREAD

**Issue by zeptonaut** [google/trace-viewer#1015]
[`Selection`](https://github.com/google/trace-viewer/blob/daf0ac06efd45fa7105f9f8523b336baff0cc0e1/trace_viewer/core/selection.html) is in a weird state where it has some array-like features (like increasing in length when `push()`ed onto, `forEach()`, `map()`, `every()`, and `some()` methods, allowing direct access through `[]`) but not all (it's missing other functions that arrays allow, like `reduce()`). In reality, `Selection` is an Object and Selection[0] is actually creating a '0' property on the `Selection` object. It's like an array... but not.

The naive (but wrong) solution to this would be to make `Selection` have `Array` as its prototype instead of `Object`. However, this isn't possible because v8 doesn't deal well with things that extend `Array`.

Another reasonable option would be to rename `Selection` to something like `SelectionSet` and to remove its array-like features. Instead, have it be backed by an array that can be accessed via some `toArray()` method. This carries a risk that someone could manipulate that array directly, but this risk exists already, as someone could overwrite any property on the `Selection` property that they choose.

Doing this would allow us to use other `Array` features with `Selection`; for example, now, where we can't do:
    
    selection.reduce(function(x, y) { ... });

we could, in the new world, do:

    selection.asArray().reduce(function(x, y) { ... });

We could also delete our custom implementations of `map()`, `every()`, `forEach()`, and `some()`.

@natduca suggested `EventSet` for the name of the new class: I'm not opposed to this, so long as we remove all selection-specific logic from the class. In the code, we should still refer to any `EventSet`s related to selection as `selection` or `selectionSet`.

**Comment by zeptonaut** [comment]
@natduca @dj2 What do you guys think the new name should be? I'm partial to renaming it to `SelectionSet` for now, which will get us most of the gains without having to kill off all of the selection-specific logic in the class. I'm definitely open to other arguments though.

**Comment by natduca** [comment]
I'd like to move away from the word selection here. Here's the thing. We are a brushing ui, in the sense that as you move your "brush" [dragging, clicking links] the state of the UI adjusts. Originally, the brush state was just the things you had clicked --- aka the selection --- so Selection was a good word. But, over time, we added find controller, and we're adding "highlight links when you hover them", and we have subviews who highlight related events when you select them, and other cool stuff like that. That means that the currently selected and related and highlighted etc items is a complex thing...

Now interestingly, these days, we use Selection objects to just refer to a bunch of events. A list of slices, etc. It has nothing to do with what is highlighted, brightened, etc. So, my sense is EventSet might make sense.

As a side comment, the thing manages all these different brushing items is called the SelectionController. But internally, you'll notice it has a thing called BrushingState. So, probably we should rename that to BrushingController, and ditch the word selection entirely from the codebase, except where there is a precise notion of the user selecting *exactly* one thing.

**Comment by dj2** [comment]
Selection is more like....InteractionState? I'd avoid having the implementation type (Set) in the name as it could change in the future.

Looks like  there are a few things in selection:
 * sunburst zoom level
 * selected event GUIDs
 * duration of time the selection covers (this is the bounds)

It then also has methods to retrieve those methods in specific ways like organized by type or by title.

I'm actually guessing sunburst zoom level should be removed from there as I think it's the wrong place for it. But, conceptually, a user interacts with the UI and we end up with this set of state. The interaction could be a find, a select a hover. Zoom level would fit with that as well as zooming is an interaction.

**Comment by natduca** [comment]
Hmm a few things: sunburst zoom level is going away... when #706 is fixed, the sunburst state goes up to the brushing state and selection doesn't have to hold that. The reason its there is because the sunburst stuff wanted to work well with back/forward and at the time selection objects held the state.

Since then, I realized something kinda important ... the "Selection" class isn't actually state. Its just a collection of events. The fact that it represents state only happens when we connect it to a particular thing, like a sub-view or the selection(aka brushing) controller. So thats why I went for a collection-oriented name. We use selections all over the analysis code to just represent a group of events... which is why selection has a ton of methods for grouping and processing events.

Set, I suggested, because selection has the property that you can add the same event twice to it and it dedupes. So, I was likening it to set in python. And, when we remove the sunburst hack, then the object really does just contain a list of events, a dict to dedupe them, grouping code, and a bounds.

**Comment by philippebeaudoin** [comment]
I would argue that a Set is an abstract data type, not an implementation.
There are a number of ways of implementing a set, but they all have in
common the fact that they do not keep the objects in a specific order and
they dont allow repeated objects. I believe these two properties are
essential to the-class-formerly-known-as-Selection and therefore I'm
partial to the name EventSet.

Also, having just used Selection for something that wasn't in any way a
selection -- and having been slightly confused by the name -- I can only
cast my vote in favor of a move to a more generic name.

**Comment by dj2** [comment]
Sounds good, EventSet works for me.

**Comment by natduca** [comment]
@dj2 sounds like you made headway on this?

**Comment by dj2** [comment]
Selection has been renamed EventSet.

**Comment by natduca** [comment]
So the remaining thing is to remove the []-hack on the selection object?

**Comment by zeptonaut** [comment]
Yep. It probably just makes sense to wrap some sort of an internal `events_` array and provide some getter that allows access to that array.

**Comment by PhilBeaudoin** [comment]
Just to add my +1 to this: I was bitten by the fact that EventSet push() doesn't support variable arguments and my eventSet.push.apply(eventSet, eventList) didn't work. I support getting rid of this array-like API.

**Comment by natduca** [comment]
Might be good to make EventSet.push.apply work fwiw. But as far as us having EventSet.events = [], YES GOD YES. :)

**Comment by PhilBeaudoin** [comment]
Good point, we do need to keep EventSet.push() around since it does guid-based deduping.

This actually highlights an important danger of exposing the backing array: we should make sure it's read-only somehow or we run the risk of someone mistakenly doing eventSet.events.push(...) or some other write modifs that could wreak havoc.

**Comment by zeptonaut** [comment]
We don't have any support for Immutable Arrays
<https://github.com/facebook/immutable-js> in TV, do we?

On Fri, Jul 17, 2015 at 6:27 PM, Philippe Beaudoin <notifications@github.com
> wrote:

> Good point, we do need to keep EventSet.push() around since it does
> guid-based deduping.
>
> This actually highlights an important danger of exposing the backing
> array: we should make sure it's read-only somehow or we run the risk of
> someone mistakenly doing eventSet.events.push(...) or some other write
> modifs that could wreak havoc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/trace-viewer/issues/1015#issuecomment-122435693>
> .
>



-- 

Charlie Andrews | Software Engineer | charliea@google.com

**Comment by natduca** [comment]
My understanding is that [currently] freeze() based techniques comes at a pretty hefty penalty.

Possibly, the way to deal with this is that the events array be private, e.g. eventSet.events_, and we not expose the array itself ever. Then we expose the various array/map/filter functions, which produce new eventSets. At worst, we can add a getItemAtIndex() and a get length() getter. But hopefully the existing arraylike functions will suffice.

**Comment by zeptonaut** [comment]
I think that I'd probably prefer having an `events` method that just
returns a copy of the backing `events_` array. Manually implementing, or
even piping through, all of the array methods sounds like a bummer, and
copying arrays isn't too expensive.

On Fri, Jul 17, 2015 at 8:48 PM, Nat Duca <notifications@github.com> wrote:

> My understanding is that [currently] freeze() based techniques comes at a
> pretty hefty penalty.
>
> Possibly, the way to deal with this is that the events array be private,
> e.g. eventSet.events_, and we not expose the array itself ever. Then we
> expose the various array/map/filter functions, which produce new eventSets.
> At worst, we can add a getItemAtIndex() and a get length() getter. But
> hopefully the existing arraylike functions will suffice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/trace-viewer/issues/1015#issuecomment-122461632>
> .
>



-- 

Charlie Andrews | Software Engineer | charliea@google.com

**Comment by philippebeaudoin** [comment]
At that point my preference is for not exposing the backing array. If we expose it via a copy and it doesn't look like an expensive operation then we run the risk of generating countless copies just for iterating. 

This is an abstract Set type and as such should expose typical methods of that datatype: a mechanism to iterate (in no guaranteed order), a mechanism for getting-or-adding, etc. The fact that there is a backing array is an implementation detail that shouldn't be exposed IMHO. If we really need a toArray doing a copy at some point then we can consider it, but exposing it to save the trouble of building the right interface for EventSet would be a mistake IMHO.

In that sense, I think EventSet is not in a bad place right now, maybe some methods are a bit badly named. For example Push gives the impression that it behaves like an array, not a set (I was bitten by this) but otherwise I prefer status quo to the systematic use of toArray for iterating.

**Comment by natduca** [comment]
the thing to remember is that we've already implemented the arraylike
methods. So there's no work here. The work comes if we expose the events
array. So my leaning is to keeping with the sealed architecture, to avoid
work basically. I do think that Charlie you're right that there exists some
possible architecture for eventset that is based around immutability and
copying. I do think though that the parts of the eventset API in that case
might be awkward since Js doesn't have an intrinsic set object.

**Comment by zeptonaut** [comment]
It sounds like there's no great way to provide access to the underlying array without some other nasty consequences that we don't want. It sounds, though, like everyone agrees that we should get rid of the []-hack on the `EventSet` in favor of some cleaner set interface and a hidden array that backs the set.

**Comment by natduca** [comment]
Heck yeah!
