### ISSUE TITLE
Use a hierarchical layout for the Related Events table in analysis view.

### ISSUE THREAD

**Issue by philippebeaudoin** [google/trace-viewer#1019]
Right now the Related Events table can become quite cluttered (see screenshot). It would be useful to turn the table into a hierarchy with "Flow", "Connected Events" and "Slice Hierarchy" as subcategories.

![image](https://cloud.githubusercontent.com/assets/11399419/8110990/1455f43c-102d-11e5-83df-a21cb1506fcd.png)

**Comment by dj2** [comment]
One other question I had. The group on the right takes up a lot of screen space. Can we instead move that into it's own tab instead of sharing space with the regular analysis view? (The analysis panes can become wide, having to scroll horizontally is a bit of a pain)

**Comment by philippebeaudoin** [comment]
I think that right table could be made much thinner by default, which would work well with its current placement.

One thing I agree with, though, is that it feels a bit weird to associate it with the "slices" tab. It feels like these are events related to you whole selection, not just to the "slices" in your selection. As such it should be a top-level component. (ie, side-by-side with the tabbed panel allowing you to view slices, flow events, etc.)

Pinging @natduca for opinions.

**Comment by natduca** [comment]
Wondering if a basic bug is the left part of the multi-event-selection view.

If you have

```
[          a                ]  [      b        ]
      [     b     ] [  c  ]
```

Right now, when sel=[a,b,b] we show 2 b's and one a. When you have this, though, the totals become bonkers because the "b" time is included in a, for instance.

Is the right thing to pause thinking about relateds for a bit, and make the left hand side work hierarchically? E.g. take all the slices and find only the ones that are toplevel, then turn those into a tree view that shows
```
  a
    b(1)
  b(2)
````

Thinking out loud. Open question whether the subrows off of a should be [b1, c] or just [b1]. Open to suggestions.
