### ISSUE TITLE
Sync ipcs are hard to represent with flow events

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1023]
Suppose you have a task a and b. a has a flow event out to b. and b has a flow event back to a. This would happen when trying to represent a sync ipc.

We currently draw flow arrows from the end of the start slice, to the start of the end slice. That leads to this:

![photo on 6-11-15 at 3 03 pm](https://cloud.githubusercontent.com/assets/412396/8119582/79e4b400-104b-11e5-817e-e549e2a7ff21.jpg)

The question is, how should we represent sync ipcs and other related nested message loops in the model, and the ui?

**Comment by dj2** [comment]
Do you have an example trace where this happens? This seems like the slices are wrong ...

**Comment by dj2** [comment]
One thing we could try is, having a new type of flow event that binds to the timestamp. So, when we record the flow we specify the slice it's bound too (for navigation purposes) but we also bind the timestamp it refers too. Then, when we draw it, we draw the arrow pointing to the timestamp, so it would appear in the middle of the parent block at the point when the execution returned to the original slice.

Repointing to the start I think is wrong because it doesn't give an accurate representation of how time flowed through the slices.

**Comment by natduca** [comment]
We actually keep ahold of the timestamp of the flow event start/end events, currently, but then just use the timestamp of the slices-to-which-its-bound during drawing. We could probably switch back to using those old timestamps and see if it works... maybe I was thinking too hard about this!

[one minor tweak we might try there is to clamp the timestamp to the slice that its bound to, so that the flow event would never point 0.001ms before the start of the slice, but would instead at that point be pointing at the start of the slice]
