### ISSUE TITLE
BattOr importer tests failing on ToT

### ISSUE THREAD

**Issue by aschulm** [google/trace-viewer#1044]
Seems like there is an issue with the recent changes to counter sample and counter series. I am investigating it now.

Also, my CL for #1012  didn't have the tv->tr change in it, so it's failing.

**Comment by petrcermak** [comment]
If you can't fix it quickly, then please revert and reland once it's resolved. Also, please **always pull the latest <tt>origin/master</tt>, rebase, and test your patch locally before landing**. Thanks :wink:

**Comment by aschulm** [comment]
Reverted. Looks like there are two issues, one is I didn't test the rebase before landing so I missed the tv->tr change (I'll never do that again), and two is there seems to be already being addressed in #1038.

**Comment by petrcermak** [comment]
Thanks! *[Don't worry about it :wink: This is something that the presubmit script should probably take care of in the future]*

The second issue should hopefully be relatively easy to work around: don't import the files which cause a circular dependency. It's (temporarily) fine if your tests fail when they run *on their own* (due to missing dependencies) as long as they pass when *all tests* are run (i.e. some other test files import your dependencies).
