### ISSUE TITLE
Continued refinements to units/

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1057]
What's awesome about units/ right now is that we can now have strongly typed data separated out from its display.

Whats less awesome is that the array_of_numbers_span only works for scalar numbers. If we wanted it to work for bytes, stamps, durations, etc, we'd have to make a whole lot of new widgets, a ArrayOfTimeStampsSpan, etc. That's not so good because we know we want lots of visualization capabilities inside the ArrayOfX spans.

Thus, I'm wondering if there exists a world where we have a Unit object, which has common unit operations, then a UnitSpan and a ArrayOfUnitsSpan that use the unit operations for formatting.

Then, TimeStamp would be a number plus a pointer to the TimeStamp unit, and a TimeStampSpan would just contain a UnitSpan.

We have some of this already in place in the time.html file, which defines various time units. So maybe this is just about generalizing that a bit further...

**Comment by natduca** [comment]
@petrcermak @benshayden @zeptonaut fyi

**Comment by petrcermak** [comment]
Ideas/problems/feature requests merged from other issues:

* There is a lot of **code duplication** between <tt>TimeStamp</tt> and <tt>TimeDuration</tt>. The same applies to <tt>\<tr-ui-u-time-stamp-span\></tt> and <tt>\<tr-ui-u-time-duration-span\></tt>.
* The current implementation of <tt>\<tr-ui-u-time-duration-span\></tt> is **not flexible** because it does too many things — unit formatting, warnings, font style, text alignment, and sparkline. As a result it cannot be reused in non-tabular contexts (e.g. timeline view drag box).

**Comment by petrcermak** [comment]
An associated issue I came across today:

The style of different unit spans is now inconsistent in many single selection analysis sub-views:

![screenshot from 2015-07-17 14 01 27](https://cloud.githubusercontent.com/assets/2546601/8747659/b5c95b76-2c8c-11e5-9be2-2c5b1765c4de.png)

The reason for this is that, unlike all other fields/units, **<tt>\<tr-ui-u-time-duration-span\></tt> changes font and text alignment**. The unbounded right alignment is especially problematic when the window is maximized.

@natduca @paulirish FYI

**Comment by natduca** [comment]
I think this is a pretty serious visual regression. Wanna file a fresh bug about this and mark it p1 and assign to me?
