### ISSUE TITLE
Initial perf_insights implementation

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1063]
We want to get a basic map_traces and wr implementation going.

Design:
https://docs.google.com/document/d/1-UsAgxNbu4v2TiFpOga_yAjfBm2bEbTk5MHMwz1Voig/edit#

**Comment by anniesullie** [comment]
I have tons of questions! I'll start with the big ones:

  1. What's the output of the "Map Traces" step? How is the data meant to be used?
  2. What does the "index" step on upload do? I assume "DS" is datastore, what is stored there?

**Comment by fmeawad** [comment]
1- Map traces will generate a dict like object for each trace. These dicts are to be aggregated in the WR.
2- Index is simply built over the given metadata with any trace. But that in most cases not enough for an efficient Clustering (by the corpus selector). So we might need to extract information from the trace efficiently and store them as well.

**Comment by anniesullie** [comment]
Looking at https://docs.google.com/document/d/1Eumpf5ts7FL_L2eJeKorjYV42nRxdqD-vOyZlA2hH6U/edit#, the dicts from map traces include RAIL scores, and stats on anti-patterns and also some atttribution info? So the mapper has the ability to parse out the trace model, RAIL interaction records, audits, etc, but it doesn't store any type of intermediary format, just the output the current version of the weather report dashboard will show?

How will the corpus selector do clustering? In the diagram, it looks like the corpus selector will always query the index. But it seems like some of the things we'd want to cluster on would be output by the mapper. Why doesn't the mapper generate some queryable datastore?

**Comment by fmeawad** [comment]
We will probably add a memcache on the mapper output, that part is still being refined.

The mapper scripts will change more frequently, so its output might not be robust enough for something to be stored in the data-store. So we need an intermediate step that creates the trace-model for each trace and extract more metadata to store in the data-store. Which leads to another idea which is storing the whole trace-model, which would make the trace-mappers more efficient. (idea still under consideration)

I don't think reliably clustering on memcache is a good idea since it can change.

At the moment the system is designed from right to left (i.e. upload then cluster) and as we finish those parts we will refine the design for the remaining components.

**Comment by natduca** [comment]
#984 is effectively done, so work can now begin on this.
