### ISSUE TITLE
<tr-ui-u-time-duration-span> sparkline cannot be disabled

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#1074]
The current implementation of sparkline (which is, by the way, awesome!) <tt>\<tr-ui-u-time-duration-span\></tt> doesn't support disabling the sparkline. As a result, there is a **light blue vertical line on the right side of the span** even when <tt>durationSpan.percentage = undefined</tt>:

![screenshot from 2015-07-01 15 20 44](https://cloud.githubusercontent.com/assets/2546601/8456660/d10d930a-2004-11e5-856b-8a3f104cadc3.png)

In some situations, this can also lead to the **sparkline overlapping other elements** (CPU Self Time Totals sparkline overlaps other totals):

![screenshot from 2015-07-01 15 07 10](https://cloud.githubusercontent.com/assets/2546601/8456501/c7e3e384-2003-11e5-8bd5-2b15ad4216c5.png)

**Comment by paulirish** [comment]
>  As a result, there is a light blue vertical line on the right side of the span

I was hoping `border-box` plus `width:0` would make computed size 0, but I suppose I'm not so lucky. :)

> (CPU Self Time Totals sparkline overlaps other totals)

We shouldn't have sparklines at all in the totals row, so that may be my bug. 

Anyhow. review of [your CL](https://codereview.chromium.org/1216053010/) coming

**Comment by petrcermak** [comment]
On a more general note, I think that the sparkline should be separate from <tt>tr-ui-u-time-duration-span</tt> for several reasons:

  1. **Code reuse**. Other elements are likely to use this amazing feature in the future as well (e.g. <tt>tr-ui-u-size-in-bytes-span</tt>) and I'd like to avoid re-implementing it multiple times.
  2. **Flexibility**. Right now the time duration span encapsulates not only number+unit formatting, but also font style (monospace) and alignment (right). While this is great in the table view (such as <tt>tr-ui-a-multi-event-summary-table</tt>), it makes the element unusable in other contexts (such as the <tt>TimelineTrackView</tt> drag box).

This should be very easy to do given that the <tt>duration</tt> and <tt>percentage</tt> fields are completely independent (a sign that the element should be split into two).

**Comment by natduca** [comment]
I'm not sure I agree that they should be separate actually. I think the
real thing we should focus our energies on is the unit unification. We
shouldn't have to have three spans for time stamps, durations and sizes.
There should be one Unitish span, with some side code for unit formatting.
That Unitish span can then support percentages.

**Comment by petrcermak** [comment]
I agree that we have too many units at the time (I'm especially unhappy about the code duplication between <tt>tr-ui-u-time-*stamp*-span</tt> and <tt>tr-ui-u-time-*duration*-span</tt>). My concern is that a single <tt>tr-ui-u-unit-span</tt> element would be doing *too many things* (unit formatting, font style, text justification, sparkline, ...), which would make it too rigid for some contexts (like the dragbox). My feeling is that composition would work well here:

```
<!-- table cell contents -->
    <tr-ui-u-sparkline percentage="0.5">
        <tr-ui-u-unit value="1024" type="size">
        </tr-ui-u-unit>
    </tr-ui-u-sparkline>
<!-- end of table cell contents -->
```

**Comment by natduca** [comment]
I think we should split your componentization request to a separate bug, wanna file one? Or move it to our uber doc of concerns around units? I still don't agree and I have reasons but this bug can be fixed I think.

My rationale btw is that separating out to a sparkline span is premature because you're tryign to architect what we *have* vs what we *want to have.*

Think about the percentage value for a moment. Its not like we have here two unrelated widgets, a number display and a thermometer display. Rather, we have a widget that is showing a bit of text, then a bar that is scaled to relate to the nearby other siblings. The "percentage" is just "context".

In my head, I think of the percentage field as a short term thing, but in the future we'd rename it to be "siblings" and then we'd give that a list of sibling united numbers that it relates to. The percentage would then just be computed internally by the widget and their siblings...

**Comment by petrcermak** [comment]
I see the point about the percentage and value widgets not being unrelated and like the idea of "siblings". Maybe it's really just the textual formatting (42 → "42.000 ms") that should be separate from the widget itself so that it could be reused.

Yeah, I think it would be better to move all unit-related discussion to #1057...

This issue is now **fixed** BTW.
