### ISSUE TITLE
Custom Colors for Slices

### ISSUE THREAD

**Issue by shikexue** [google/trace-viewer#1091]
For extending trace viewer for other projects or visualizations, it's useful to be able to specify the colors of the slices to fit the particular project. The particular project that this is relevant for is creating timeline views using CQ data for Chromium developers. An example [here](http://chromium-cq-status.appspot.com/patch-timeline/1219623006/40001), where passing tests are colored green and failed ones are colored red.

I've worked on it in this [CL](http://chromium-cq-status.appspot.com/patch-timeline/1227903005/1), but there were concerns about separating data from the visualization. What is the view on such a feature?

**Comment by petrcermak** [comment]
Thanks for creating a dedicated issue for this! I think that rather than having events with green and red *color*:

```
...
{ ... event1 data ..., 'cname': 'green'},
{ ... event2 data ..., 'cname': 'red'},
...
```

it would be better to give them a passed and failed *state* (or something along those lines, I'm not sure what the best names are here):

```
...
{ ... event1 data ..., 'state': 'passed'},
{ ... event2 data ..., 'state': 'failed'},
...
```

Does that sound reasonable?

@dj2, @natduca: WDYT?

**Comment by dj2** [comment]
I guess the question with using state is, would different projects want different colours for the same states? Are we just going to end up back in the same position 6 months down the road where the CQ wants failure to be red and project foo wants failure to be purple?

**Comment by natduca** [comment]
cname seems fine as long as it maps directly to the color scheme file in base and the naming matches exactly what we have for the getColorIdByBlah in there.

What I want to avoid is custom color specification by the file: the key to trace-viewer performance is that all color processing is palettized. That allows the fast rect renderer to do some simple tricks that keep drawing performance fast in the face of lots of slices.

As far as different projects wanting different colors, that is gonna be tough, since the palette would need to be chosen at import time. As such, I could somewhat imagine allowing the color palette to be on trace options and then passed around to the tracks, but its some real refactoring. I'd avoid this as long as we can since we really wanna focus on PI-related goals as much as is humanly possible.

**Comment by shikexue** [comment]
Closing issue as CL has been committed.
