### ISSUE TITLE
Normalize webapp2 handler filenames: x_handler.py contains XHandler

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#1134]
Seems like we typically name files and classes by their type. Yet we have perf_insights/upload.py which contains a RequestHandler class.

Just trying to learn convention here.

@anniesullie @fmeawad

**Comment by anniesullie** [comment]
The perf dashboard left out "_request_handler" from all the file names because initially all the .py files were request handlers. But now we have a lot of files and it is hard to tell which ones are request handlers. So it probably wasn't the best convention.

@qeny, any opinions?

**Comment by qeny** [comment]
My opinion: Adding "_handler" to the modules with handler classes sounds reasonable to me. I would prefer _handler rather than _request_handler.

Pros: It would make it clearer which ones aren't request handlers, and then module names for modules which contain classes would be the same as the class names they contain (e.g. alerts_handler.py contains AlertsHandler)
Cons: Longer file names.

Another (not mutually exclusive) change would be to move all of the request handlers to a separate directory.

Some notes about the modules in dashboard/ (excluding dashboard/models):

 - Excluding the unit tests, there are 77 modules and about 50 are request handlers.
 - The base classes currently have _handler in the file name (request_handler.py, chart_handler.py, slave_post_handler.py).
 - The non-handler classes include things like dispatcher.py, utils.py, oauth2_decorator.py, and stored_object.py.

**Comment by qeny** [comment]
Note: Another possible name for perf_insights/upload.py would be upload_page.py, if we wanted to have  a convention of naming all request handler classes that serve HTML pages as something_page.py. (The current name of the request handler class in that module is UploadPage). Although this maybe isn't the best name, since that handler has a post() method which doesn't give a HTML page as a response.

Anyway, the main reason to avoid changing the names to end in _handler or _request_handler is then the names would be longer (buildbucket_job_status.py would then be buildbucket_job_status_handler.py, and it's test would be buildbucket_job_status_handler_test.py). But I think this would be OK.

**Comment by fmeawad** [comment]
or maybe we can create a directory called handlers and/or change the names.

**Comment by natduca** [comment]
My typical preference is to choose to move things to a module when they warrant a module, not as a way to deal with naming convention issues. That is, if we want a module for handlers, thats fine but its an orthogonal concern relating to code structure. The concern here is following predictable, normative convention, so I'd suggest we settle on "class implies filename" conventions:
- class names are XHandler
- file names are x_handler.py

For instance, in the perf insights, I'm not sure we really need a handlers folder yet. But, we can be normative in our naming of files there right off the bat.

Of course, if we choose go to the module format, then we'd drop the _handler.py suffix, as this is already convention in python, as @fmeawad correctly points out.
