### ISSUE TITLE
"Hide instant events" checkbox

### ISSUE THREAD

**Issue by paulirish** [google/trace-viewer#800]
Some traces spam instant events which end up throwing big vertical lines in the UI. 
Ideally we can toggle them off sometimes.

**Comment by dj2** [comment]
Can we, instead either fix those events or turn them into disabled-by-default if the team needs them? Having the toggle buttons gets confusing when you forget you've toggled them on/off.

Do you have a list of events that are causing issues?

**Comment by natduca** [comment]
I think I'd be okay with a hide button here, since it can get a bit annoying. I do agree we should encourage people to not use instant [paul, lets file a crbug to normalize the devtools events to be tracing friendly].

I think a precursor to a patch that does this work should probably adjust the Ui so that all the checkboxes are in a hover-to-expand menu --- we've got two checkboxes now so h-space is getting a bit tight. :)

**Comment by paulirish** [comment]
>  [paul, lets file a crbug to normalize the devtools events to be tracing friendly].

yup definitely

**Comment by paulirish** [comment]
FWIW, this is what inspired the ticket, for me at least.

![image](https://cloud.githubusercontent.com/assets/39191/6543642/af3fdff8-c4d8-11e4-97fb-48639d99951f.png)

Anyway, it will be dealt with on the instrumentation side.

**Comment by natduca** [comment]
We now have a dropdown (#801) so if we want to add more checkboxes like this, we're good to go.
![image](https://cloud.githubusercontent.com/assets/412396/7551030/8698f144-f62d-11e4-8607-d67db151aa3a.png)

fyi @petrcermak @ChrisCraik
