### ISSUE TITLE
Add means to rewrite slice names

### ISSUE THREAD

**Issue by ChrisCraik** [google/trace-viewer#818]
Would like to rewrite names to ensure consistency across data sources, and simplify the job of Auditors in these cases.

E.g. in L, "getDisplayList" (a name for an internal method) become "Record View#draw()" to better describe what it does.

**Comment by natduca** [comment]
So the question I'm wondering here is how to ensure that all the different ways you can create a slices get rewritten. There're a lot of places that create slices, eg various importers, plus unit tests... which should get rewritten and which shouldn't?

Having auditors do a rename after import is possibly the "makes sure you catch everything" solution here. That way all slices get renamed, which would be nice.

This having been said, I worry about changing names mid-audit: I've thought about adding down the road code to add an index on slice names to the model to help make auditors faster. But, if auditors are changing names, then mayhem could ensue.

So maybe auditor objects should have a few passes? Instead of the generic RunAudit method they have now, maybe we should tweak it to be two steps, DoRenames, DoAdutis? Then we could do indexing after the renames pass?

**Comment by ChrisCraik** [comment]
That works for renaming, but there are several other model annotations that I can see auditors or trace model extensions making - things like linking slices that it knows to be connected (either with arrows, or in extra arguments). We could say they can add arguments and edit names, or is that an arbitrary cutoff?

**Comment by dj2** [comment]
So, we already have something like this. The end of import loops over everything, moving arguments, creating layer trees, etc. Can we make these two things the same?

At the end of import, we create the Auditors, then they control the post-process stage. At that point,the auditor can change anything they want, when post-process is done the model is 'frozen' and shouldn't be modified.

**Comment by ChrisCraik** [comment]
Now in use for a few Android alerts: https://github.com/google/trace-viewer/commit/0c6bc796fa9ccb35212bc70987bb3573f72ca931
