### ISSUE TITLE
CounterTrack should function when timestamps on each series are discontinuous

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#832]
Right now counters have to have all the same timestamps. This makes complex graph data hard to add to the uI.

**Comment by natduca** [comment]
@aschulm fyi

**Comment by petrcermak** [comment]
Here's the new design of chart tracks we discussed today:
![img_20150326_124742](https://cloud.githubusercontent.com/assets/2546601/6857944/99291600-d3c7-11e4-90c1-5fe5428a023f.jpg)

Summary:

* <tt>ChartTrack</tt> is the new *model-agnostic* common class for all chart tracks (<tt>CounterTrack</tt>, <tt>GlobalMemoryTrack</tt> in the future, ...). It has a list of <tt>series</tt> sorted in z-order. This class is responsible for *calculating/transforming the coordinates* of all points.
* <tt>ChartTrackSeries</tt> is an abstract class corresponding to a single series on the track (e.g. a line connecting dots). It has an <tt>axis</tt>, a list of <tt>values</tt> (each of which must provide a <tt>ts</tt> and a <tt>y</tt> coordinate) and a <tt>colorId</tt>. This class is responsible for *drawing the chart* for a particular series (given the coordinates calculated by <tt>ChartTrack</tt>) The visual style of the series depends on the actual implementation:

    * <tt>LineChartTrackSeries</tt> (line chart).
    * <tt>AreaChartTrackSeries</tt> (area chart).

* <tt>Axis</tt> defines the <tt>range</tt> of displayed <tt>y</tt> values. Every <tt>Axis</tt> has a unique <tt>guid</tt> because multiple <tt>ChartTrackSeries</tt> can share the same axis.

**Comment by petrcermak** [comment]
In order to be able to visualize stacked area charts, we need to be able to set the **base y-coordinate** of a <tt>ChartPoint</tt>. The screenshot below shows a single chart series where the points around the *left* peak have the *default* base y-coordinate (i.e. <tt>undefined</tt>), whereas the points around the *right* peak have *custom* base y-coordinates:

![y_base](https://cloud.githubusercontent.com/assets/2546601/7586233/b3f0706e-f8a2-11e4-8ccd-6671cae78656.png)

I uploaded a patch with the proposed change (https://codereview.appspot.com/234430043) which adds support for base y-coordinate to <tt>ChartPoint</tt> and <tt>ChartSeries</tt>.

__Problem__

There are two things that complicate rendering the bottom side of a bar chart series:

  1. Multiple adjacent bars (with the same selection state) are drawn together as one polygon (as opposed to drawing each bar separately as a rectangle) to avoid visual glitches. The problem is that the bottom side of the polygon must be drawn in **reverse chronological order** – from right to left.
  2. Points that would be too close together are skipped or shifted to avoid visual glitches. This means that we **cannot simply walk the list of array of points backwards** to draw the bottom side of the polygon.

__Solution__

To address these issues, we build a list of the corresponding bottom coordinates as we draw the upper side of the polygon. Afterwards, we traverse the list in a reverse order and draw the bottom side.

Note that if two adjacent points have the same base y-coordinate, then there is no need to store both in the list of bottom coordinates. We thus only need to store the bottom coordinates at which the base y-coordinate changes (i.e. the visual bottom "steps").

__Performance comparison__ (on existing tracks where all points have the default base y-coordinate)

Current implementation (custom base y-coordinates not supported):

Iterations|Mean|Standard deviation
--------|-------|-------
1|56.547 ms|9.445 ms
10|30.120 ms|1.785 ms
100|27.651 ms|1.482 ms

Proposed implementation

Iterations|Mean|Standard deviation|Difference
--------|-------|-------|--------
1|65.408 ms|5.248 ms|+15.67% *(regression)*
10|31.730 ms|2.290 ms|+5.35% *(regression)*
100|27.318 ms|0.436 ms|-1.20% *(improvement)*

The performance difference is relatively small for 10 and 100 iterations (both are within one standard deviation) and is probably caused by *noise* in the measurements.

There appears to be a statistically significant difference between the performances with a single iteration. I suspect this is only due to V8 taking slightly longer to compile the code for some reason and should therefore have no impact on user experience.

__Open question__

It is still not clear to me if/how custom base y-coordinates should affect **<tt>ChartAxis</tt> autosetting**. I can think of several approaches:

  1. Ignore custom base y-coordinates (proposed implementation)
  2. Treat custom base y-coordinates as regular y-coordinates (i.e. auto-size axes with both _y_ and _yBase_ for each <tt>ChartPoint</tt>)
  3. Add an extra optional flag to the <tt>ChartAxis.autoSetFromRange</tt> config (e.g. <tt>config.includeBaseY</tt>)

I opted for the first approach because the other two approaches would require modifying the <tt>ChartSeries.range</tt> getter (probably to a regular function <tt>ChartSeries.getRange(includeBaseY)</tt>).

**Comment by natduca** [comment]
This sounds great. Let's make sure we aren't creating garbage for the
cached locations though... We don't want to increase gc pauses due to each
redraw creating garbage
