### ISSUE TITLE
Analysis view missing timing info if single slice selected

### ISSUE THREAD

**Issue by ChrisCraik** [google/trace-viewer#851]
Recent regression: If a single slice is selected, timing isn't shown:
![missingtiming](https://cloud.githubusercontent.com/assets/384439/6832668/1abb1594-d2e5-11e4-8446-902c393df80d.png)

**Comment by petrcermak** [comment]
Found another example of (most probably) the same regression. This one happens when you select a single **counter sample**:
![screen shot 2015-03-25 at 13 52 05](https://cloud.githubusercontent.com/assets/2546601/6835392/a363500c-d2f7-11e4-95b8-9a2c286807a1.png)
The issue seems to be associated with **polymer** because the hidden elements are polymer objects.

**Comment by petrcermak** [comment]
I bisected the issue and it was caused by 8d19410, which seems plausible because it refactored <tt>GenericObjectView</tt> (which is not showing) to Polymer.

**Comment by petrcermak** [comment]
This issue affects several elements that have been recently *polymerised*:

* <tt>generic-object-view</tt>
* <tt>generic-object-view-with-label</tt>
* <tt>time-span</tt>
* (possibly other elements...)

The bigger problem is that **all tests pass despite the actual elements being hidden**. We should figure out some way to test that this is not the case. Currently, the only semi-automatic way is to check if the <tt>X_instantiate</tt> tests show anything or not.

**Comment by dj2** [comment]
Fixed.
