### ISSUE TITLE
Double clicking on RulerTrack no longer creates guide line

### ISSUE THREAD

**Issue by ChrisCraik** [google/trace-viewer#895]
Used to do this a long time ago, was an extremely useful feature for correlating events across time

**Comment by natduca** [comment]
@jackjyang wdyt?

**Comment by jackjyang** [comment]
This is really simple to do, especially now that we have x_marker_annotations.

I think this is also a good opportunity to implement a way to copy a shareable find nav string (the 2555@124.236x5 thing). I'm imagining a UI for this something like: a user clicks and drags down from the ruler onto the timeline where a horizontal line and vertical line will follow the cursor. At the same time the find box on the top right will be populated by the nav string of the current position of the cursor. Once the user releases the drag, the horizontal line, vertical line, and the find-box string remains so that they can copy it. The lines will be cleared once the user clears the text in the find box.

The original idea was to make this part of an annotation tool but thinking about it now this feature isn't really part of drawing an annotation. I think doing it this way will capture the use case as described by Chris too. Thoughts? cc @dj2

**Comment by jackjyang** [comment]
Marking this as resolved. Feature has been added to draw an x marker annotation after clicking on the ruler and dragging down. This also creates a string in the find box that someone can copy and send to someone else, who then can paste to quickly navigate to the same view of the timeline

**Comment by natduca** [comment]
So awesome, thanks jack!

**Comment by ChrisCraik** [comment]
I'd like to reopen this - I'm getting a lot of people trying the new UI, and asking for behavior of the the old double-click lines back.

First, double clicking is already the standard interaction for this for systrace users and it would be nice to add support for that interaction back.

Second, one single line isn't as useful as being able to create many, separating some chunk of execution into several stages.

**Comment by natduca** [comment]
I'm fine with bringing this back! Can you write the patch?

**Comment by ChrisCraik** [comment]
Will do.
