### ISSUE TITLE
Add auditor that turns telemetry's interaction record into trace-viewer's interaction records with proper associatedEvents

### ISSUE THREAD

**Issue by nedn** [google/trace-viewer#897]
Context:
Telemetry supports the notion of interaction records marked by the app/users directly. For example, to create a "telemetry interaction record" in chrome trace, one can do:

var str = 'Interaction.SendEmail';
console.time(str);
setTimeout(function() {
    console.timeEnd(str);
}, 1000);

https://code.google.com/p/chromium/codesearch#chromium/src/tools/telemetry/telemetry/web_perf/timeline_interaction_record.py&l=83

Trace-viewer should recognize these interaction records output by telemetry and turn them its interaction record so they show up on top of the screen, instead of just async events in renderer threads.

**Comment by natduca** [comment]
Seems good. I think we should have IR's moved to mark/measure first though? @zeptonaut was slowly working on that...

**Comment by nedn** [comment]
Why is this blocked on IR's moved to mark/measure? I think they are orthogonal?

**Comment by natduca** [comment]
Well, lemme put it this way... where do you want to do this detection and conversion?

**Comment by nedn** [comment]
In trace-viewer's code? This is after the interaction record has been written to the trace, so I think how it's written to the trace shouldn't matter, unless mark/measure changes its event types from async event to s.t else.

**Comment by natduca** [comment]
The main concern I had was that the format would change. If this is always going to be an async slice [before and after] then we're good. At one point, we were going to make different trace event types for mark/measure, though I believe we've changed our plan more recently. Again, its worth sanity checking this.

In trace-viewer code, there are two places we could put this: one is in the trace_event_importer, two is in auditor.

Doing this in the importer is fishy because we're saying that some magic async slice name automatically turns into an interaction record. That's pretty funky, wouldn't you agree? At that point, we really should have a custom event for IRs.

Doing this as an auditor is a bit better: making a telemetry_auditor that recognizes traces from telemetry and looks for any async slices and creates IRs for them feels plausible. If we go that route, we may not care how the IR is represented in the file.

**Comment by nedn** [comment]
Totally agree that auditor is better.  importer code shouldn't make any assumption about specific states of the trace data.

**Comment by natduca** [comment]
Sg. Lets update the bug title.
