### ISSUE TITLE
Nanosecond precision event placing

### ISSUE THREAD

**Issue by egonelbre** [google/trace-viewer#927]
Layouting with nanoseconds doesn't work nicely. (On the dev server you can see it in [Nanoseconds example](http://localhost:8003/examples/trace_viewer.html#nanoseconds.json)).

*From my debugging. It seems that the time_event is affecting the layouting of the events and affects how it's miscalculated. Tried to fix with https://codereview.appspot.com/217470043/, but it wasn't up to bar.*

Current behavior:
![Current](https://cloud.githubusercontent.com/assets/192964/7295654/ee29a32c-e9c0-11e4-9172-95c03d75507b.png)

Expected behavior:
![Expected](https://cloud.githubusercontent.com/assets/192964/7295657/f9026e78-e9c0-11e4-86e2-92287e4e82cd.png)

Trace:
```json
{
  "traceEvents": [
    {"name": "us1", "ph": "B", "pid": 1, "tid": 1, "ts": 0},
    {"name": "us1", "ph": "E", "pid": 1, "tid": 1, "ts": 1.1},
    {"name": "us2", "ph": "B", "pid": 1, "tid": 1, "ts": 1.1},
    {"name": "us2", "ph": "E", "pid": 1, "tid": 1, "ts": 1.3},
    {"name": "us3", "ph": "B", "pid": 1, "tid": 1, "ts": 1.3},
    {"name": "us3", "ph": "E", "pid": 1, "tid": 1, "ts": 1.6},
    {"name": "us4", "ph": "B", "pid": 1, "tid": 1, "ts": 1.7},
    {"name": "us4", "ph": "E", "pid": 1, "tid": 1, "ts": 2.1},

    {"name": "ns1", "ph": "B", "pid": 1, "tid": 1, "ts": 3.000},
    {"name": "ns1", "ph": "E", "pid": 1, "tid": 1, "ts": 3.011},
    {"name": "ns2", "ph": "B", "pid": 1, "tid": 1, "ts": 3.011},
    {"name": "ns2", "ph": "E", "pid": 1, "tid": 1, "ts": 3.013},
    {"name": "ns3", "ph": "B", "pid": 1, "tid": 1, "ts": 3.013},
    {"name": "ns3", "ph": "E", "pid": 1, "tid": 1, "ts": 3.016},
    {"name": "ns4", "ph": "B", "pid": 1, "tid": 1, "ts": 3.017},
    {"name": "ns4", "ph": "E", "pid": 1, "tid": 1, "ts": 3.021}
  ]
}
```

**Comment by dvyukov** [comment]
/cc @natduca 

Yes, that's what I saw -- lots of randomly stacked spans on the same row, when I expected them to be nicely line up.

**Comment by natduca** [comment]
This data are useful as it explain why subrow grouping was needing work. Thank you.

This points out that the Slice.bounds function is making an incorrect assumption about the maximum precision of the model data. In a typical trace event file, the assumed precision is microseconds, whereas in these files, the precision is higher.

I tend to think we need to first have the model have some field like timeResolution. Where it is by default 0.001.

And, remember, there are multiple importers so we need to be correct in that case: if one file has precision=0.001 and another has precision=0.000001 we should probably use the smaller.

So, model probably wants a method like updateMinimumTimePrecision(precision) that takes the min of that and the previous, if any. 

Then,, for traceEventImporter calls updateMinimumTimePrecision when it runs. If a file wants precision other than 0.001, then it should have a field precision: <number> that the importer reads. Go would need to output that field.

That would be patch one.

Then, patch two is to modify event.bounds(event) to be event.bounds(model, event) where the bounds logic reads the model precision as part of the math, and the callers of the bounds function pass in the model.

Bonus points for a patch that renames event.bounds to something more obvious, like event.doesEventContain(otherEvent) or something.

**Comment by dvyukov** [comment]
Nat, can you explain what is wrong with just rounding to nanoseconds?
Current code always rounds to the minimum resolution (assuming that the current minimal resolution is microseconds). Egon's change just changes the assumption about the minimal resolution without changing anything else, adding complexity or making the code worse in another other sense. The change looks like the right way to fix the issue to me.
What you propose extends the model and adds additional abstractions. Is it necessary? Why? What problem does it solve? Do we really need to do in the context of this fix?

**Comment by dvyukov** [comment]
Just to clarify, what you propose looks like much more work. I want to make sure that we really need to do it rather than get away with the spot fix and be done with this issue.

**Comment by natduca** [comment]
Just rounding to nanoseconds will cause stacking to change in files that have microsecond precision.

**Comment by dvyukov** [comment]
I am just trying to understand the problem we are solving with the more complex implementation, because the simpler change is much faster to implement and review (in fact, it is already implemented). For now I do not see how the change can affect traces with microseconds.
For the rounding change to affect traces with microseconds, the error in timestamp calculations must be larger than 1ns. According to http://www.w3schools.com/js/js_numbers.asp javascript numbers are 64-bit floats with 52-bit mantissa. "end = start + original_end - start" calculation can give at most 2 bits of error (each addition gives half of a bit). So the *1000 change can affect traces with microseconds only if microsecond timestamps are larger than (52-10-2) bits = 2^40/1000/1000/60/60/24 days =~ 13 days.
Now, size of a single event is roughly equal to 100 bytes (even if we take X events like "{"name": "myFunction", "cat": "foo", "ph": "X", "ts": 109951162700, "dur": 234, "pid": 2, "tid": 2},"). If we emit a single such event every 100ms for 2^40 microseconds, size of the trace file will be equal to: (2^40/100000)*100 = 1099511627 bytes = 1 GB.
Trace viewer does not support such large inputs. So the *1000 change cannot affect traces with microseconds.

**Comment by natduca** [comment]
Please do the implementation I suggested. I am quite sure it is needed. Thank you.

**Comment by egonelbre** [comment]
Just realized that I wasn't getting any updates from this issue before.

@natduca I can now understand the reluctance to simply change the resolution - magic constant adjustment problems tend to crop up again and again.

Regarding the method name `x.bounds(y)` and `x.doesEventContain(y)`, there are also `x.containsEvent(y)` and `y.happensDuring(x)`.

From the analysis that @dvyukov made, it sounded like the problem might have not been in trace_viewer itself, but instead something else. I started digging and the precision fix was introduced in 980f9ed1694678a579bdd332f07acfba1969. Basically the difference happens in "X Event Trace" example. Comparison:
![comparison](https://cloud.githubusercontent.com/assets/192964/7316147/3789bcc0-ea7d-11e4-8ae6-63ab3950d81d.png).

I'm guessing the importer is computing the start/duration in this way:

```js
var trace_start = 172187584349 / 1000;
var x = 172189236812 / 1000 - trace_start;
var x_duration = 1 / 1000;
var y = 172189236813 / 1000 - trace_start;
var y_duration = 0 / 1000;

console.log(last_event, x, x + x_duration, y);
// 1652464 1652.4629999995232 1652.4639999995231 1652.4639999866486
```

So, if we do inside the importer:

```js
var trace_start = 172187584349;
var x = (172189236812 - trace_start) / 1000;
var x_duration = 1 / 1000;
var y = (172189236813 - trace_start) / 1000;
var y_duration = 0 / 1000;

console.log(last_event, x, x + x_duration, y);
// 1652464 1652.463 1652.464 1652.464
```

We can get rid of the precision error and get rid of the magic constant in bounds check. Of course, I'm not quite sure where to start attacking this issue.

Anyways... regardless of my comments, I've started on the approach suggested by @natduca ATM.

**Comment by natduca** [comment]
@egonelbre this is awesome work, <3 this level of thinking, its an example of the kind of "lets go figure out the fundamental hard problem" kinda work that enables a team to work at scale on hard problems. Thank you for both taking the time to dig in, and being persistent in the place of pushback from cranky people like myself!

I totally agree that we'd have better precision characteristics if we moved the timeshifting first. But we don't currently have a way to get the trace start time at the right place... let me try to provide some context....  the import flow is sort of like this:

importTraces(array of traces) {
  importers = find importer for each trace
  foreach importer
    importer.importEvents()
  find trace_start
  shift world to zero
}

The last step is what does the subtraction of trace_start component. The /1000 is done in the run import step(s). So to do what you're suggesting, I think we need to somehow find the minimum timestamp in the model before we run the importer.

Interestingly, #856 has a similar desire: sometimes we have to import multiple traces that all have different clock domains. For instance, we may want to import a trace from the ddms importer AND also the linux kernel trace. These have different clock domains, but each trace will internally contain a sync record that says "linux_clock 70 equals ddms clock 33". To get those data, we want to add a step before importEvents that walks over the trace model and finds all the clock sync records and adds to the model a list of clock domains. Then, instead of every model doing /1000 conversion inline, it would instead go to the model and say "getModelTime(clock_domain, timestamp)" and internally that would do 

Now, the reason I bring this up is the following: to get clock domains, we end up walking through the entire event array anyway. So we could also get the minimum timestamp in each importer, too... that way we could have every clock domain know the timebase, too. Meaning, the same system that cleans up clock domain coordination might actually enable us to do the math you suggested!

Anyways, an approach like this would be a much harder patch than the architectural thing I suggested, but it actually sounds like it might be the better one for the project, and solve both the ns problem and the #856 bug too...

Great discussion! Thanks for digging deeper.

**Comment by egonelbre** [comment]
> Thank you for both taking the time to dig in, and being persistent in the place of pushback from cranky people like myself!

First rule of code-reviews, don't blame the reviewer and when sides disagree, assume some information is missing from the conversation. :)

Sounds good.

Although, I'm not sure about adding time-domain to the model. It feels like the Importing doesn't belong to TraceModel, when there is this much complexity in the process. I would remove the Importer dependency from TraceModel and introduce a separate some sort of Importing context that would handle importing/dialogs/time-domains/ and building TraceModel up there. Basically, adding time domain to TraceModel would fragment the importing code even more.

**Comment by natduca** [comment]
Well importing already is on trace model: TraceModel.importEvents. ^_^

But it is indeed mostly self contained. I agree, there could tear TraceModel.importEvents and ImportOptions off of TraceModel into Importer.html or something. But thats more code cleanup... the patch above wouldn't really increase chaos there much more that I'd block the feature on the refactoring.

**Comment by egonelbre** [comment]
I've been thinking about this issue. Nat, how do you feel about using the precision constant modification to make the nanoseconds mode usable. Obviously, leaving the issue open and replace that modification with the harder patch once it is completed. *PS: Don't worry saying no, I can understand, if you oppose to it.*

**Comment by natduca** [comment]
So you know how we were talking in the other bug about how to set the default time unit by adding a uint field to the trace event file, and then propagating that to the model's intrinsicTimeUnit field?

How about once you add that, you could have the subrow builder use that property for rounding. Add a method to unit that does the right rounding for ns and ms for instance (roundForSubRowBuilding). Then the subrow builder would go this.model.intrinsicUnit and ask it to do the rounding.

Then all that remains is to get the model from the slice group object. I bet that's not too hard to do... worst case, we make the SliceGroup constructor take a parent object, and then modify all constructors of SliceGroup to pass in the parent: threads, in all cases. All threads know their model, so then you're okay.

**Comment by egonelbre** [comment]
It seems that changes in https://codereview.appspot.com/246010044/ for some reason fixed this issue. I don't yet understand why... :/

**Comment by egonelbre** [comment]
It seems that SliceGroup (except in tests) already has access to the model.

Anyways, I've created https://codereview.appspot.com/241420043/ but didn't mail it yet, because it feels like a hack-job. This doesn't feel nice for me.

**Comment by egonelbre** [comment]
Note, that the example is now working. I'm currently leaving this open so that some of the precision issues from importing can be removed. Although, I suspect that we still cannot remove the roundedLess from time units. There are still places that can introduce small precision errors. It's probably less fragile if the roundedLess stays in place.
