### ISSUE TITLE
Allow async grouping preference to be chosen by data instead of code

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#961]
We have a lot of hand-coded customizations to grouping:

https://github.com/google/trace-viewer/blob/master/trace_viewer/extras/net/net_async_slice.html#L28
https://github.com/google/trace-viewer/blob/master/trace_viewer/extras/gpu/gpu_async_slice.html

The main goal in both cases is to allow the grouping to be different than the title, by overriding viewSubGroupTitle. In the net case, there's actual logic that runs that we couldn't remove. And in the gpu case, there's logic that changes color for beauty reasons. But its common for folks to want grouping to be based on, say, tid, or 

How about we add a field to async events that, when present, sets the viewGroupTitle explicitly?

e.g. 

 {ph: 'b', name: 'async_grouping_mode', group: 'blah'},
 {ph: 'e', name: 'async_grouping_mode', group: 'blah'}

would end up with other async slices with blah as their group name.

**Comment by natduca** [comment]
@xunjieli @dj2 wdyt?

**Comment by dj2** [comment]
So, for the GPU case, they'd output Device.blah or Service.blah in the group entry? And in Net they'd output NetLog?

**Comment by xunjieli** [comment]
Is it possible to group according to the Category name? so we can avoid having an extra field.
NetLog events are under "NetLog" category. For GPU, I am assuming they have their own categories.

**Comment by DavidYen** [comment]
For GPU they all share the same category names but use a separate "Channel"
argument to specify the group preference. What Nat suggested would handle
everything the gpu_async_slice does.

**Comment by xunjieli** [comment]
Ah, I got what you mean. My only concern is whether adding "group" will make the code harder to reason about in the future. Since Async events are already been grouped by "category", if we have another field that these events can be grouped by,  won't it become confusing? It will be nicer if we can still use "category" to do grouping for gpu's use case. How about including Channel ID as a part of the name for the category, sth like "disabled-by-default-gpu.device.channelX"? Then events belong to that channel will automatically be grouped together. Not sure whether it'd be feasible though.
