### ISSUE TITLE
Toplevel AsyncSlices top-bars have differing alpha depending on panning

### ISSUE THREAD

**Issue by natduca** [google/trace-viewer#971]
This is due to how the fast rect renderer draws their top bar.

**Comment by natduca** [comment]
@xunjieli

**Comment by natduca** [comment]
I think I have a fix, on it...

**Comment by xunjieli** [comment]
Thanks, Nat! I don't really understand the code, but the fix is awesome :)
Btw, I think you might have forgotten to check isTopLevel when drawing the topbar. Now all nestable async slices have a topbar.

After the change:
![screenshot from 2015-05-22 09 43 29](https://cloud.githubusercontent.com/assets/1412855/7771709/62af167a-0067-11e5-9cd3-ac2ac7d40774.png)

Before the change (only some of the slices should have a top bar):
![screenshot from 2015-05-22 09 41 50](https://cloud.githubusercontent.com/assets/1412855/7771720/72d53458-0067-11e5-8bbb-a93c72e7aec5.png)

Although http://localhost:8003/examples/trace_viewer.html#../test_data/nestable_async.json looks fine.. Not sure what is wrong.

**Comment by natduca** [comment]
Whoops! I'll fix now...

**Comment by natduca** [comment]
Hopefully better now!

**Comment by xunjieli** [comment]
Verified locally. This is very cool. Thanks!
