### ISSUE TITLE
Remove buffer percent full dialog.

### ISSUE THREAD

**Issue by dj2** [google/trace-viewer#972]
We have the buffer percent full dialog being displayed which will cause the process to query all processes every n seconds. This is going to add cruft into the actual traces themselves.

We should remove this dialog completely and stop the calls from happening. This means we can probably also remove the plumbing from the chrome side as well.

**Comment by yury-s** [comment]
Trace buffer may get full quite quickly and it'd be convenient if the user was at least notified when the buffer is full. This may be implemented as an event sent by the browser to tracing UI. Does it make sense?

**Comment by dj2** [comment]
The problem is, no-one ever sees the full notification because trace-viewer is in a tab behind the current tab. So, we update the UI, but it isn't useful.

We could possibly do something where when we render the trace we mark up that the buffer filled and was cut off, would also be nice for continuous so they know the beginning was chopped as well. This still has the benefit that it removes updates during the trace itself.

**Comment by petrcermak** [comment]
Don't forget that the tracing tab is visible *the whole time* when tracing *Chrome for Android*.

**Comment by dj2** [comment]
Are you saying that you can see the buffer percentage when tracing android? (I've never traced android so I have no idea what it looks like). Is the buffer full percentage useful in this case?

**Comment by petrcermak** [comment]
If you trace Chrome *for Android* by navigating to <tt>chrome://inspect?tracing</tt> on Chrome *for desktop*, then you see the tracing dialog with buffer percentage on your desktop the whole time (because there's no need to switch tabs on the desktop since you are tracing the Android device).

**Comment by dj2** [comment]
Good to know. Do you find you refer to the buffer percentage when you're recording? Is it actually useful?

**Comment by benshayden** [comment]
When I record a trace on android, I watch the buffer percentage about half the time and the screen about half the time.
If the buffer percentage were removed, then I might keep swiping for a minute and be annoyed when it only captured 10 seconds.
If the buffer percentage were removed but it stopped tracing and automatically collected and displayed the trace when the buffer was full, I would be so happy.
Twopence.

**Comment by petrcermak** [comment]
That's exactly my feeling – I watch the % only to make sure that I don't lose the start of the recording.

**Comment by dj2** [comment]
I believe, the case you described above is what will happen if you used the fixed size buffer. As soon as it's full the trace stops and it starts display the trace. Do you have 'Record Until Full' selected or 'Record Continuously'. The former should stop and the latter will over-write.

You can also use 'Record as much as possible' which should also get you more content, or may crash chrome when it runs out of memory, heh.

**Comment by benshayden** [comment]
Are those command line options? I don't see them in the Record dialog.

![972](https://cloud.githubusercontent.com/assets/1566089/7846548/0ebf1668-0473-11e5-90e4-980930934b25.png)

**Comment by petrcermak** [comment]
The options are not in Chrome stable yet. You need to use a newer version (e.g. compile Chromium from source).

**Comment by dj2** [comment]
You can enable Record-until-full in that version of chrome by unselecting Continuous Tracing. That should then cause the trace to auto-finish and load when the buffer is full.

If you want Record-as-much-as-possible then you need a newer Trace-Viewer (and possibly newer chrome), so, yea, build from source.

**Comment by natduca** [comment]
This seems harder to resolve. I like Yury's idea of the proto telling the ui when its full, and maybe a warning, but not a continuous update.

@anniesullie this should be in a backlog somehow for trace platform as its clearly impacting the correctness of traces. As such, I think this deserves a P1 marker.

**Comment by natduca** [comment]
Dan can we assign this to you?

**Comment by dj2** [comment]
Sure. Although, I still think we don't need the notification and all the bits should just be removed.

If you care when the buffer is full, turn off continuous trace. Once the buffer is full the trace will stop and the viewer will load. If you don't care if the buffer is full use continuous trace. If you never want the buffer full, use record as much as possible.

**Comment by natduca** [comment]
I think thats a good long term plan. I think it'd be good to figure out a less catastrophic way of providing the current notification experience, since devtools uses it still.

For instance, what if child processes send an unsolicited ipc to the tracing_controller_impl when they're full, and 80% full, as a first step. We could then have the fullness notifications go up through the channel with way less overhead than before, and could even skip sending the notifications when the "total full" hasn't changed. Make sense?

**Comment by dj2** [comment]
@yury-s is devtools using the notification on buffer full percentage? How does it use it and what does it use it for?

**Comment by yury-s** [comment]
DevTools polls buffer usage periodically [1] and displays it as a progress indicator while recording Timeline. This is very similar to chrome:tracing

[1] https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/devtools/protocol/tracing_handler.cc&q=TracingHandler::OnBufferUsage&sq=package:chromium&type=cs&l=141

**Comment by dj2** [comment]
The other option is to just change our polling value a bit. We poll every 500ms, what if we polled every second instead? Would half the impact we have on the trace.

Looks like devtools uses a minimal poll interval of 250ms. So they would currently see more impact then us do to tracing triggering events.

If we're just updating a given page content, that should only effect the renderer for the trace-viewer tab, correct? The title was worse because it was adding events into the browser process itself which got messy.

**Comment by natduca** [comment]
Even if we tweak refresh rate, i think our broadcast to all processes is hurting us, especially on machines with lotta tabs. We could gently tweak this to keep the polling, but instead of tracing controller impl broadcasting to get buffer full, we could have each process ipc its %-age to the browser anytime it goes up by 10%. Then the browser can just compute the max of that, and return that. That means that one "poll" is then going to be just a round trip to the browser, and back. And, it'd be quantized, so you could poll reasonably fast and just drop data if the number hadn't changed...

I think my underlying worry here is that UX pressure is to set the refresh rate high ... if you turn it to 0.5s then we'd get more "ack it dropped data" complaints. I don't think we can say "you're doing it wrong" for devtools use case. Or put another way, I think that us just using the polling rate as our fix for this is just going to endlessly jostled us between two valid goals: ux on one side and perf on the other.

**Comment by dj2** [comment]
I like the idea of the processes reporting up in x% increments and then browser just sending back a value on poll.
